### ISSUE TITLE
[Suggestion]: Epilog Mini Support

### ISSUE THREAD

**Issue by ryanrapini** [EpilogLaserCorp/epilog-print-api-release#1]
### What would you suggest?

Hi there!

I am currently setting up an Epilog Mini that I purchased secondhand and coming from the 3d printer world I'm really disappointed in the experience setting up a laser. The Epilog software feels extremely dated and clunky, and worse still, the Print Driver interface renders with tiny text that i cannot read.

Are there any plans to bring modern support to these legacy machines? I bought an Epilog laser on the recommendation that these machines are high in quality and last for many years. If this is true, will you not support these lasers with modern software?

Thank you for your time.

**Comment by tylers-epilog** [comment]
Hi @ryanrapini, sorry that your experience has been lack-luster!

From your description, I believe that using our newest Software Suite would greatly improve your experience. While this new version isn't always marketed for the older machines like the Mini, it is certainly compatible, so feel free to give it a try!

You can find that here:
https://www.epiloglaser.com/support/drivers/fusion-edge-maker-pro-drivers/ (or [direct download](https://www.epiloglaser.com/assets/downloads/drivers/epilog-software-suite/EpilogSuite_2.2.15.2_x64.zip))

Also, for future reference, this form is only for supporting the Epilog PrintAPI which is a separate product meant for software developers. Our support department (https://www.epiloglaser.com/support/) will be happy to assist you with any future issues.
